services:
  - type: web
    name: schoolmedix-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run dev
    autoDeploy: true
    pullRequestPreviewsEnabled: true
